apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-ecommerce-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
     app: site-ecommerce
  template:
    metadata:
      labels:
        app: site-ecommerce
    spec:
      containers:
      - name: site-ecommerce
        image: site-ecommerce:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080