apiVersion: v1
kind: PersistentVolume
metadata:
  name: site-ecommerce-pv
  labels:
    app: site-ecommerce-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/tancrede/Documents/TPKube/getting-started-app-main/data
    type: DirectoryOrCreate