apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-ecommerce-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: site-ecommerce-pv